# Generated by Django 2.0.6 on 2018-06-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='box',
            table='box',
        ),
    ]
