# Generated by Django 2.0.6 on 2018-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180606_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='area',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
            preserve_default=False,
        ),
    ]
